apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.15.0-alpine
        ports:
        - containerPort: 89

        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-conf #nome do volume
          readOnly: true

#criacao volume
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf #nome do config map
          items:
            - key: nginx.con
              path: nginx.conf
