apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app

spec:
  selector:
    matchLabels:
      app: app

  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: img-deployment
        ports:
        - containerPort: 80
        #variaveis de ambiente

        #puxando o password que setei no meu passwordsecret
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password

        envFrom:
        - configMapRef:
            name: app-conf

        #montar Volume
        volumeMounts:
        - name: app-conf
          mountPath: /var/www/.env
          subPath: .env

      #definicao Volume
      volumes:
      - name: app-conf
        configMap:
          name: app-conf
          items:
            - key: env
              path: .env

